// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWPK6YOK65w1mSVh969SN-3Jkprd2VPTU',
    appId: '1:662850750993:web:38ec747e0f2d68e99ebfb0',
    messagingSenderId: '662850750993',
    projectId: 'counseling-management-system',
    authDomain: 'counseling-management-system.firebaseapp.com',
    storageBucket: 'counseling-management-system.firebasestorage.app',
    measurementId: 'G-X127R0S4KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdsxusr6XEdcNDAQDCgBqebNV7JHu8sM',
    appId: '1:662850750993:android:69faf25a99bf96de9ebfb0',
    messagingSenderId: '662850750993',
    projectId: 'counseling-management-system',
    storageBucket: 'counseling-management-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT4S4r5xmhpSchgdqpR6blxob7oOVa6UU',
    appId: '1:662850750993:ios:e9c769d0decf098f9ebfb0',
    messagingSenderId: '662850750993',
    projectId: 'counseling-management-system',
    storageBucket: 'counseling-management-system.firebasestorage.app',
    iosClientId:
        '662850750993-qb0s0tb5ee6m172pg3kiqo8sagun3a8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT4S4r5xmhpSchgdqpR6blxob7oOVa6UU',
    appId: '1:662850750993:ios:e9c769d0decf098f9ebfb0',
    messagingSenderId: '662850750993',
    projectId: 'counseling-management-system',
    storageBucket: 'counseling-management-system.firebasestorage.app',
    iosClientId:
        '662850750993-qb0s0tb5ee6m172pg3kiqo8sagun3a8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWPK6YOK65w1mSVh969SN-3Jkprd2VPTU',
    appId: '1:662850750993:web:3500d92238546a489ebfb0',
    messagingSenderId: '662850750993',
    projectId: 'counseling-management-system',
    authDomain: 'counseling-management-system.firebaseapp.com',
    storageBucket: 'counseling-management-system.firebasestorage.app',
    measurementId: 'G-W50JHKHZSY',
  );
}
